baseURL = "https://datosh.github.io/"
languageCode = "en-us"
title = "DaTosh Blog"
theme = "github.com/lxndrblz/anatole"
summarylength = 10

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'nord'
    tabWidth = 4
    wrapperClass = 'highlight'

[params.mermaid]
enable = true

[params]
title = "DaTosh Blog"
author = "DaTosh"
# description = "Blog"
profilePicture = "images/Profile.jpg"
contentratio = 0.75
doNotLoadAnimations = true
copyright = "2020-{{ YEAR }}"


[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/datosh"

[[params.socialIcons]]
icon = "fab fa-x-twitter"
title = "twitter"
url = "https://twitter.com/datosh18"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/fabian-kammel-7781b7173/"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "Talks"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[menu.main]]
  name = "Side Projects"
  weight = 400
  identifier = "sideprojects"

  [[menu.main]]
  name = "GoInvaders"
  parent = "sideprojects"
  weight = 410
  url = "/goinvaders/game.html"

  [[menu.main]]
  name = "Pin GH Actions"
  parent = "sideprojects"
  weight = 420
  url = "https://pin-gh-actions.kammel.dev/"

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false
