# de requires additional dictionary to be installed
# https://www.npmjs.com/package/cspell-dict-de-de
language: en, de
files:
  - '**/*.md'
allowCompoundWords: true
caseSensitive: false
words:
  - brrrrrr
  - datosh
  - traefik
  - unRAID
  - VAAPI
  - runningvms
  - acpipowerbutton
  - Merkury
  - controlvm
  - startvm
  - PPPOE
  - dnsnet
  - pfsense
  - lxndrblz
  - kubeadm
  - kubectl
  - Kubestronaut
  - kammel
  - SDXL
  - cyclonedx
  - syft
  - GHSA
  - SLSA
  - println
  - errorf
  - unmarshal
  - distroless
  - sboms
  - NTIA
  - edgelesssys
  - opnsense
  - ryzen
  - kanidm
  - rauthy
  - cifs
  - kubelet
  - nfsvers
  - exportfs
  - libaio
  - ioengine
  - EZRZ
  - HSTS
  - drcc
  - bwvvf
  - jftn
  - zjks
  - dearmor
  - dpkg
  - nodeadkeys
  - qcow
  - vcpu
  - snet
  - dmacvicar
  - qlen
  - noqueue
  - qdisc
  - UEFI
  - virt
  - libvirtd
  - connectorid
  - gpgsign
  - Priya
  - Wadhwa
  - goinvaders
  - ebiten
  - glfw
  - pygame
